### ISSUE TITLE
Update: The Event Calendar and Pods Conflict Fix

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-docs#86]
## Issue Info
* Docs URL:  https://docs.pods.io/code-snippets/event-calendar-pods-conflict-fix/
* Doc Title: The Event Calendar and Pods Conflict Fix
* Issue Type: Update

## Issue Description
The description says "bit of cold" instead of "bit of code."

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] Overview Created
- [ ] Quick Start (if Needed) Created
- [ ] Excerpt Created for Summary
- [ ] Keywords, Difficulty and Context completed
- [ ] Related Docs, Videos, FAQs, Code Snippets referenced
- [ ] Code Review Completed (if needed)

From: Thomas Brown thomas@happypixelco.com

**Comment by sc0ttkclark** [comment]
I guess it was cold that day.

Fixd.
